name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: build (Elixir ${{ matrix.elixir }} | OTP ${{ matrix.otp }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Elixir 1.15 supports OTP 24-26 (minimum version)
          - elixir: '1.15'
            otp: '24'
          - elixir: '1.15'
            otp: '25'
          - elixir: '1.15'
            otp: '26'
          # Elixir 1.16 supports OTP 24-26
          - elixir: '1.16'
            otp: '25'
          - elixir: '1.16'
            otp: '26'
          # Elixir 1.17 supports OTP 25-27
          - elixir: '1.17'
            otp: '25'
          - elixir: '1.17'
            otp: '26'
          - elixir: '1.17'
            otp: '27'
          # Elixir 1.18 supports OTP 26-27 (and likely 28)
          - elixir: '1.18'
            otp: '26'
          - elixir: '1.18'
            otp: '27'
          - elixir: '1.18'
            otp: '28'
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Restore deps cache
        uses: actions/cache@v4
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
      - name: Restore _build cache
        uses: actions/cache@v4
        with:
          path: _build
          key: build-${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
      - name: Reset Hex archive (avoid OTP mismatch)
        run: |
          mix archive.uninstall --force hex.ez || true
          rm -rf ~/.mix/archives/hex-* || true
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix compile --warnings-as-errors
      - run: mix test
        env:
          ELIXIR_ASSERT_TIMEOUT: '2000'

  dialyzer:
    name: dialyzer (latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18'
          otp-version: '28'
      - name: Restore deps cache
        uses: actions/cache@v4
        with:
          path: deps
          key: deps-${{ runner.os }}-latest-${{ hashFiles('**/mix.lock') }}
      - name: Restore _build cache
        uses: actions/cache@v4
        with:
          path: _build
          key: build-${{ runner.os }}-latest-${{ hashFiles('**/mix.lock') }}
      - name: Reset Hex archive (avoid OTP mismatch)
        run: |
          mix archive.uninstall --force hex.ez || true
          rm -rf ~/.mix/archives/hex-* || true
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix compile
      - run: mix dialyzer

